### PR TITLE
chore: clean up homepage above the fold area

### PR DESCRIPTION
**Pull request by WJakub**
* Install tailwindcss (will speed up FE styling tweaks and offer more clarity/ improved DX for those just wanting to contribute from time to time)
* Cleanup the CTA buttons on the homepage to improve visual hierarchy
* Add max-width to the hero title/text, on large screens it was too wide to read nicely

Just getting into the swing of finding time to help out on the project, wagmi.

**Screenshots**
Screenshot 2023-05-16 at 07 15 08
Screenshot 2023-05-16 at 07 14 50

### CODE REVIEW

**Comment by chimera-defi** [comment]
Think we def want the logo to be bigger, closer to its current size for mobile and laptops. 
Seeing 300px X 300px on the Logo on the landing page. We want to keep the aspect ratio around the same. 
Can we try to use EM

**Comment by WJakub** [comment]
yessir @chimera-defi - will get round to it after work tonight.

**Comment by WJakub** [comment]
@chimera-defi Made further tweaks:
* Fixed up the hero logo sizing
* Further cleanup of the hero styles/layout
* Improved hero on mobile
* Removed the popup, the content now lives on a terms of service page
* Cleaned up the Privacy, FAQ and ToS pages to be more legible
* Replaced their footer links with router links & scroll to top behaviour

**Review by chimera-defi — APPROVED** [review]
LGTM! Great work!

**Pull request merged**
